### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/relay_counter#1]
![Screenshot from 2021-02-06 23-55-04](https://user-images.githubusercontent.com/8411656/107137082-f8b78980-68d6-11eb-8194-fd1c955e8480.png)
Finally got caught up enough to look at this relay counter.
running a 5 block sample but not succeeding.
here's the config
{
  "timeline": {
    "start": -5,
    "end": 0,
    "unit": "blocks"
  },
  "endpoint": "http://localhost:8082/v1",
  "http_retry": 3,
  "params": {
    "blocks_per_session": 4,
    "approx_block_time_in_min": 15
  }
}

Thoughts?

**Comment by BenVanGithub** [comment]
Got it running... super sweet little piece of code .. thanks so much.. I'm gonna have a hundred uses for this baby.
BTW:  problem seems to have been caused by running on outdated client 0.5.2.3.   Only machine I havent upgraded is the one I use for personal testing... LOL

**Comment by andrewnguyen22** [comment]
Closing due to using older version of Pocket Core
