### ISSUE TITLE
please include minHeight and maxHeight values in report header

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/relay_counter#2]
After playing with it a bit.. I kinda think that it really needs to accept absolute block numbers in addition to relative to current block time periods. as well as printing same in the report file.
 
I would find it much easier to run batches and keep them organized by month or week or whatever if the header info contained min and max height.
Thank you.

**Comment by andrewnguyen22** [comment]
closed with c785c10ca2a803573d9e41b2d1ab18d369acd578
