### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by bulutcambazi** [pokt-network/relay_counter#3]
- Can you please provide command line args to override config params for the timeline? I will invoke this tool periodically, and changing config file programmatically each time is less than ideal. Doable, of course. But ugly. 
- Can you please make the output name configurable via command line? Current way of auto-creating filenames is not very programmer friendly.

**Comment by andrewnguyen22** [comment]
Hey @bulutcambazi sorry seeing this a million years later
